NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.org1.kevin.chaindesk.cn-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.org1.kevin.chaindesk.cn-cert.pem
    OrganizationalUnitIdentifier: peer
