version: '2'

networks:
  basic:

services:
  ca.org1.kevin.chaindesk.cn:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.kevin.chaindesk.cn
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.kevin.chaindesk.cn-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/443a08649d8b71d5bcbe72b04147d1e9b54f1dac00a667e313a55a22497b6f07_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/org1.kevin.chaindesk.cn/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.kevin.chaindesk.cn
    networks:
      - basic

  orderer.kevin.chaindesk.cn:
    container_name: orderer.kevin.chaindesk.cn
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=kevin.chaindesk.cn
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/kevin.chaindesk.cn/orderers/orderer.kevin.chaindesk.cn/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/org1.kevin.chaindesk.cn/peers/peer0.org1.kevin.chaindesk.cn/:/etc/hyperledger/msp/peerOrg1
    networks:
      - basic

  peer0.org1.kevin.chaindesk.cn:
    container_name: peer0.org1.kevin.chaindesk.cn
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.kevin.chaindesk.cn
      - CORE_PEER_ADDRESS=peer0.org1.kevin.chaindesk.cn:7051
      - CORE_PEER_LOCALMSPID=org1.kevin.chaindesk.cn
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./crypto-config/peerOrganizations/org1.kevin.chaindesk.cn/peers/peer0.org1.kevin.chaindesk.cn/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/org1.kevin.chaindesk.cn/users:/etc/hyperledger/msp/users
        - ./channel:/etc/hyperledger/configtx
    depends_on:
      - orderer.kevin.chaindesk.cn
      - couchdb
    networks:
      - basic

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.kevin.chaindesk.cn:7051
      - CORE_PEER_LOCALMSPID=org1.kevin.chaindesk.cn
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.kevin.chaindesk.cn/users/Admin@org1.kevin.chaindesk.cn/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - basic
    #depends_on:
    #  - orderer.kevin.chaindesk.cn
    #  - peer0.org1.kevin.chaindesk.cn
    #  - couchdb
